# Generated by Django 3.2.10 on 2023-07-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carproductdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CataName3', models.CharField(blank=True, max_length=100, null=True)),
                ('ProName3', models.CharField(blank=True, max_length=100, null=True)),
                ('Proyear', models.IntegerField(blank=True, max_length=100, null=True)),
                ('ProPrice', models.IntegerField(blank=True, max_length=100, null=True)),
                ('ProDescription3', models.CharField(blank=True, max_length=500, null=True)),
                ('ProImage6', models.ImageField(blank=True, null=True, upload_to='product_photo')),
            ],
        ),
        migrations.CreateModel(
            name='Catacarsdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name3', models.CharField(blank=True, max_length=100, null=True)),
                ('Description3', models.CharField(blank=True, max_length=500, null=True)),
                ('Image6', models.ImageField(blank=True, null=True, upload_to='product_photo')),
            ],
        ),
    ]
