# Generated by Django 3.2.10 on 2023-08-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_alter_carproductdb_prokms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carproductdb',
            name='ProPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carproductdb',
            name='Prokms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carproductdb',
            name='Proyear',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
