# Generated by Django 3.2.10 on 2023-08-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkoutdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brandname', models.CharField(blank=True, max_length=100, null=True)),
                ('Carname', models.CharField(blank=True, max_length=100, null=True)),
                ('Yearman', models.IntegerField(blank=True, max_length=100, null=True)),
                ('Pricecar', models.IntegerField(blank=True, max_length=100, null=True)),
                ('Carfeature', models.CharField(blank=True, max_length=500, null=True)),
                ('Carimage', models.ImageField(blank=True, null=True, upload_to='product_photo')),
            ],
        ),
    ]
