# Generated by Django 3.2.10 on 2023-08-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwebapp', '0002_contactdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Mobile', models.IntegerField(blank=True, max_length=100, null=True)),
                ('Password', models.CharField(blank=True, max_length=100, null=True)),
                ('CPassword', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='checkoutdb',
            name='Carfeature',
        ),
        migrations.AddField(
            model_name='checkoutdb',
            name='Profuel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkoutdb',
            name='Prokms',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
