# Generated by Django 3.2.10 on 2023-08-13 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carwebapp', '0003_auto_20230811_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutdb',
            name='Carimage',
        ),
        migrations.AddField(
            model_name='checkoutdb',
            name='Register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carwebapp.registerdb'),
        ),
    ]
