# Generated by Django 3.2.10 on 2023-08-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwebapp', '0004_auto_20230813_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdb',
            name='Pricecar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutdb',
            name='Prokms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutdb',
            name='Yearman',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registerdb',
            name='Mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
