# Generated by Django 3.2.10 on 2023-08-15 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carwebapp', '0007_checkoutdb_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdb',
            name='Register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwebapp.registerdb'),
        ),
    ]
