# Generated by Django 3.2.10 on 2023-08-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwebapp', '0009_alter_checkoutdb_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutdb',
            name='Brandname',
        ),
        migrations.RemoveField(
            model_name='checkoutdb',
            name='Register',
        ),
    ]
