# Generated by Django 3.2.10 on 2023-08-16 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carwebapp', '0010_auto_20230815_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdb',
            name='Register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carwebapp.registerdb'),
        ),
    ]
