# Generated by Django 3.2.10 on 2023-08-18 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwebapp', '0012_searchresults'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchResults',
        ),
    ]
